---
service: success-handler
provider:
  name: aws
  deploymentBucket:
    name: spp-results-${self:custom.environment}-serverless
  role: arn:aws:iam::#{AWS::AccountId}:role/lambda_invoke_lambda
  vpc:
    securityGroupIds:
      - ${file(../json_outputs/security_groups_output.json):SecurityGroups.0.GroupId}
    subnetIds:
      - ${file(../json_outputs/subnets_output.json):Subnets.0.SubnetId}
      - ${file(../json_outputs/subnets_output.json):Subnets.1.SubnetId}
  runtime: python3.7
  region: eu-west-2
  memorySize: 1024
  timeout: 20
  tracing:
    lambda: true
  package:
    individually: true

custom:
  environment: ${env:ENVIRONMENT}

functions:
  deploy-success-handler:
    name: es_statistical_method_return
    handler: es_success_handler.lambda_handler
    package:
      individually: true
      include:
        - es_success_handler.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:#{AWS::AccountId}:layer:es_python_layer:latest
      - arn:aws:lambda:eu-west-2:#{AWS::AccountId}:layer:dev-es-common-functions:latest
    tags:
      app: results

plugins:
  - serverless-latest-layer-version
  - serverless-pseudo-parameters
